'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18034
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WsCalculoRetiro
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://calculo.webServices.calculoRetiroWS.ssffaa.cl", ConfigurationName:="WsCalculoRetiro.CalculoRetiroWS")>  _
    Public Interface CalculoRetiroWS
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento run del espacio de nombres  no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://calculo.webServices.calculoRetiroWS.ssffaa.cl/calcularPorParametros", ReplyAction:="*")>  _
        Function calcularPorParametros(ByVal request As WsCalculoRetiro.calcularPorParametrosRequest) As WsCalculoRetiro.calcularPorParametrosResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xmlInput del espacio de nombres  no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://calculo.webServices.calculoRetiroWS.ssffaa.cl/calcularPorXml", ReplyAction:="*")>  _
        Function calcularPorXml(ByVal request As WsCalculoRetiro.calcularPorXmlRequest) As WsCalculoRetiro.calcularPorXmlResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class calcularPorParametrosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="calcularPorParametros", [Namespace]:="http://calculo.webServices.calculoRetiroWS.ssffaa.cl", Order:=0)>  _
        Public Body As WsCalculoRetiro.calcularPorParametrosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsCalculoRetiro.calcularPorParametrosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class calcularPorParametrosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public run As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public institucion As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public subInstitucion As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public categoria As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public escalafonCivil As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public grado As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public gradoJerarquico As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=7)>  _
        Public gradoEconomico As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public esDeLinea As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public fechaDeBaja As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=10)>  _
        Public cantidadDeAcciones As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public tipoDeAcciones As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public porcentajeDeSobresueldo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public porcentajeDeSegundoSobresueldo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public porcentajeDeAsignacionSOFSOM As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public poseeAsigMinistroDeCorte As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=16)>  _
        Public sueldoIntegroMinistroDeCorte As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=17)>  _
        Public planillaSuplementariaLey19699 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=18)>  _
        Public planillaSuplementariaDFL1_68 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=19)>  _
        Public aniosCPDNyConsc As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=20)>  _
        Public mesesCPDNyConsc As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=21)>  _
        Public diasCPDNyConsc As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=22)>  _
        Public aniosDesahucio As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=23)>  _
        Public mesesDesahucio As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=24)>  _
        Public diasDesahucio As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=25)>  _
        Public otrasInstituciones As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=26)>  _
        Public abonos As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=27)>  _
        Public concurrencias As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New( _
                    ByVal run As String,  _
                    ByVal institucion As String,  _
                    ByVal subInstitucion As String,  _
                    ByVal categoria As String,  _
                    ByVal escalafonCivil As String,  _
                    ByVal grado As String,  _
                    ByVal gradoJerarquico As Integer,  _
                    ByVal gradoEconomico As Integer,  _
                    ByVal esDeLinea As String,  _
                    ByVal fechaDeBaja As String,  _
                    ByVal cantidadDeAcciones As Integer,  _
                    ByVal tipoDeAcciones As String,  _
                    ByVal porcentajeDeSobresueldo As String,  _
                    ByVal porcentajeDeSegundoSobresueldo As String,  _
                    ByVal porcentajeDeAsignacionSOFSOM As String,  _
                    ByVal poseeAsigMinistroDeCorte As String,  _
                    ByVal sueldoIntegroMinistroDeCorte As Integer,  _
                    ByVal planillaSuplementariaLey19699 As String,  _
                    ByVal planillaSuplementariaDFL1_68 As String,  _
                    ByVal aniosCPDNyConsc As Integer,  _
                    ByVal mesesCPDNyConsc As Integer,  _
                    ByVal diasCPDNyConsc As Integer,  _
                    ByVal aniosDesahucio As Integer,  _
                    ByVal mesesDesahucio As Integer,  _
                    ByVal diasDesahucio As Integer,  _
                    ByVal otrasInstituciones As String,  _
                    ByVal abonos As String,  _
                    ByVal concurrencias As String)
            MyBase.New
            Me.run = run
            Me.institucion = institucion
            Me.subInstitucion = subInstitucion
            Me.categoria = categoria
            Me.escalafonCivil = escalafonCivil
            Me.grado = grado
            Me.gradoJerarquico = gradoJerarquico
            Me.gradoEconomico = gradoEconomico
            Me.esDeLinea = esDeLinea
            Me.fechaDeBaja = fechaDeBaja
            Me.cantidadDeAcciones = cantidadDeAcciones
            Me.tipoDeAcciones = tipoDeAcciones
            Me.porcentajeDeSobresueldo = porcentajeDeSobresueldo
            Me.porcentajeDeSegundoSobresueldo = porcentajeDeSegundoSobresueldo
            Me.porcentajeDeAsignacionSOFSOM = porcentajeDeAsignacionSOFSOM
            Me.poseeAsigMinistroDeCorte = poseeAsigMinistroDeCorte
            Me.sueldoIntegroMinistroDeCorte = sueldoIntegroMinistroDeCorte
            Me.planillaSuplementariaLey19699 = planillaSuplementariaLey19699
            Me.planillaSuplementariaDFL1_68 = planillaSuplementariaDFL1_68
            Me.aniosCPDNyConsc = aniosCPDNyConsc
            Me.mesesCPDNyConsc = mesesCPDNyConsc
            Me.diasCPDNyConsc = diasCPDNyConsc
            Me.aniosDesahucio = aniosDesahucio
            Me.mesesDesahucio = mesesDesahucio
            Me.diasDesahucio = diasDesahucio
            Me.otrasInstituciones = otrasInstituciones
            Me.abonos = abonos
            Me.concurrencias = concurrencias
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class calcularPorParametrosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="calcularPorParametrosResponse", [Namespace]:="http://calculo.webServices.calculoRetiroWS.ssffaa.cl", Order:=0)>  _
        Public Body As WsCalculoRetiro.calcularPorParametrosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsCalculoRetiro.calcularPorParametrosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class calcularPorParametrosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public grados As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public sueldoEnActividad As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public sueldo1981 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public cantidadTrienios As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public porcentajeTrienios As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public asignacionTrieniosLey18263 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public asignacionTrieniosLey18694 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public porcentajeSobresueldo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=8)>  _
        Public sobresueldoLey18263 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=9)>  _
        Public sobresueldoLey18694 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public porcentajeBonifMandoAdministracion As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=11)>  _
        Public bonifMandoAdministracionLey18263 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=12)>  _
        Public bonifMandoAdministracionLey18694 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public porcentajeBonifAltoMando As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=14)>  _
        Public bonifAltoMandoLey18263 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=15)>  _
        Public bonifAltoMandoLey18694 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=16)>  _
        Public aplicaPlanillaSuplementaria As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=17)>  _
        Public planillaSuplementariaLey19699Actual As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=18)>  _
        Public planillaSuplementariaLey19699anio1981 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=19)>  _
        Public porcentajeAsignacionSOM As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=20)>  _
        Public asignacionSOMLey18263 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=21)>  _
        Public asignacionSOMLey18694 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=22)>  _
        Public porcentajeAsigMinistroDeCorte As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=23)>  _
        Public asigMinistroDeCorteLey18263 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=24)>  _
        Public asigMinistroDeCorteLey18694 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=25)>  _
        Public poseeTituloProf As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=26)>  _
        Public aegeLey18263 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=27)>  _
        Public aegeLey18694 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=28)>  _
        Public totalLey18263 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=29)>  _
        Public totalParaDesahucio As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=30)>  _
        Public cantidadAVOS As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=31)>  _
        Public montoAVOS As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=32)>  _
        Public porcentajeAVOS As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=33)>  _
        Public reajusteHasta8_8 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=34)>  _
        Public porcentajeReajusteDS376_1987 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=35)>  _
        Public montoReajusteDS376_1987 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=36)>  _
        Public porcentajeReajusteDS321_1988 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=37)>  _
        Public montoReajusteDS321_1988 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=38)>  _
        Public tipoDocUltimoReajuste As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=39)>  _
        Public numeroDocUltimoReajuste As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=40)>  _
        Public porcentajeUltimoReajuste As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=41)>  _
        Public montoUltimoReajuste As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=42)>  _
        Public totalImponibleParcial As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=43)>  _
        Public totalDesahucioSegunAvos As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=44)>  _
        Public totalImponible As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=45)>  _
        Public aegeNoImponible As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=46)>  _
        Public recibePlanillaSuplementariaDfl_1_68 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=47)>  _
        Public planillaSuplementariaDfl_1_68 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=48)>  _
        Public bonificacionCompensatoria As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=49)>  _
        Public tipoDeBonifRiesgoEspecial As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=50)>  _
        Public porcentajeBonifRiesgoEspecial As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=51)>  _
        Public bonifRiesgoEspecial As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=52)>  _
        Public porcentajeAsigMinDeCorteNoImp As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=53)>  _
        Public asigMinistroDeCorteNoImp As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=54)>  _
        Public porcentajeAsigSOMnoImp As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=55)>  _
        Public asignacionSOMnoImp As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=56)>  _
        Public porcentajeSegundoSobresueldo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=57)>  _
        Public segundoSobresueldo As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=58)>  _
        Public totalRemuneracion As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=59)>  _
        Public totalRemuneracionSegunAVOS As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=60)>  _
        Public porcentajeAVOS2 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=61)>  _
        Public pensionAotorgar As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=62)>  _
        Public conTopeSinTope As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=63)>  _
        Public distribucionCapredena As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=64)>  _
        Public distribucionFisco As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=65)>  _
        Public distribucionTotal As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=66)>  _
        Public mensualidadesDesahucio As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=67)>  _
        Public montoMensualidadDesahucio As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=68)>  _
        Public subtotalDesahucio As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=69)>  _
        Public cantidadAcciones As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=70)>  _
        Public montoUnitarioAcciones As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=71)>  _
        Public subtotalAcciones As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=72)>  _
        Public desahucioApagar As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=73)>  _
        Public mesesSgteTrienio As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=74)>  _
        Public diasSgteTrienio As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=75)>  _
        Public siguienteTrienio As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=76)>  _
        Public detalleDeServicios As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=77)>  _
        Public aniosServiciosTotales As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=78)>  _
        Public mesesServiciosTotales As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=79)>  _
        Public diasServiciosTotales As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=80)>  _
        Public enDiasServiciosTotales As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=81)>  _
        Public proporcionServiciosTotales As Double
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=82)>  _
        Public detalleConcurrencias As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=83)>  _
        Public totalConcurrencias As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New( _
                    ByVal grados As String,  _
                    ByVal sueldoEnActividad As Integer,  _
                    ByVal sueldo1981 As Integer,  _
                    ByVal cantidadTrienios As Integer,  _
                    ByVal porcentajeTrienios As String,  _
                    ByVal asignacionTrieniosLey18263 As Integer,  _
                    ByVal asignacionTrieniosLey18694 As Integer,  _
                    ByVal porcentajeSobresueldo As String,  _
                    ByVal sobresueldoLey18263 As Integer,  _
                    ByVal sobresueldoLey18694 As Integer,  _
                    ByVal porcentajeBonifMandoAdministracion As String,  _
                    ByVal bonifMandoAdministracionLey18263 As Integer,  _
                    ByVal bonifMandoAdministracionLey18694 As Integer,  _
                    ByVal porcentajeBonifAltoMando As String,  _
                    ByVal bonifAltoMandoLey18263 As Integer,  _
                    ByVal bonifAltoMandoLey18694 As Integer,  _
                    ByVal aplicaPlanillaSuplementaria As String,  _
                    ByVal planillaSuplementariaLey19699Actual As Integer,  _
                    ByVal planillaSuplementariaLey19699anio1981 As Integer,  _
                    ByVal porcentajeAsignacionSOM As String,  _
                    ByVal asignacionSOMLey18263 As Integer,  _
                    ByVal asignacionSOMLey18694 As Integer,  _
                    ByVal porcentajeAsigMinistroDeCorte As String,  _
                    ByVal asigMinistroDeCorteLey18263 As Integer,  _
                    ByVal asigMinistroDeCorteLey18694 As Integer,  _
                    ByVal poseeTituloProf As String,  _
                    ByVal aegeLey18263 As Integer,  _
                    ByVal aegeLey18694 As Integer,  _
                    ByVal totalLey18263 As Integer,  _
                    ByVal totalParaDesahucio As Integer,  _
                    ByVal cantidadAVOS As String,  _
                    ByVal montoAVOS As Integer,  _
                    ByVal porcentajeAVOS As String,  _
                    ByVal reajusteHasta8_8 As Integer,  _
                    ByVal porcentajeReajusteDS376_1987 As String,  _
                    ByVal montoReajusteDS376_1987 As Integer,  _
                    ByVal porcentajeReajusteDS321_1988 As String,  _
                    ByVal montoReajusteDS321_1988 As Integer,  _
                    ByVal tipoDocUltimoReajuste As String,  _
                    ByVal numeroDocUltimoReajuste As String,  _
                    ByVal porcentajeUltimoReajuste As String,  _
                    ByVal montoUltimoReajuste As Integer,  _
                    ByVal totalImponibleParcial As Integer,  _
                    ByVal totalDesahucioSegunAvos As Integer,  _
                    ByVal totalImponible As Integer,  _
                    ByVal aegeNoImponible As Integer,  _
                    ByVal recibePlanillaSuplementariaDfl_1_68 As String,  _
                    ByVal planillaSuplementariaDfl_1_68 As Integer,  _
                    ByVal bonificacionCompensatoria As Integer,  _
                    ByVal tipoDeBonifRiesgoEspecial As String,  _
                    ByVal porcentajeBonifRiesgoEspecial As String,  _
                    ByVal bonifRiesgoEspecial As Integer,  _
                    ByVal porcentajeAsigMinDeCorteNoImp As String,  _
                    ByVal asigMinistroDeCorteNoImp As Integer,  _
                    ByVal porcentajeAsigSOMnoImp As String,  _
                    ByVal asignacionSOMnoImp As Integer,  _
                    ByVal porcentajeSegundoSobresueldo As String,  _
                    ByVal segundoSobresueldo As Integer,  _
                    ByVal totalRemuneracion As Integer,  _
                    ByVal totalRemuneracionSegunAVOS As Integer,  _
                    ByVal porcentajeAVOS2 As String,  _
                    ByVal pensionAotorgar As Integer,  _
                    ByVal conTopeSinTope As String,  _
                    ByVal distribucionCapredena As Integer,  _
                    ByVal distribucionFisco As Integer,  _
                    ByVal distribucionTotal As Integer,  _
                    ByVal mensualidadesDesahucio As Integer,  _
                    ByVal montoMensualidadDesahucio As Integer,  _
                    ByVal subtotalDesahucio As Integer,  _
                    ByVal cantidadAcciones As Integer,  _
                    ByVal montoUnitarioAcciones As Integer,  _
                    ByVal subtotalAcciones As Integer,  _
                    ByVal desahucioApagar As Integer,  _
                    ByVal mesesSgteTrienio As Integer,  _
                    ByVal diasSgteTrienio As Integer,  _
                    ByVal siguienteTrienio As Integer,  _
                    ByVal detalleDeServicios As String,  _
                    ByVal aniosServiciosTotales As Integer,  _
                    ByVal mesesServiciosTotales As Integer,  _
                    ByVal diasServiciosTotales As Integer,  _
                    ByVal enDiasServiciosTotales As Integer,  _
                    ByVal proporcionServiciosTotales As Double,  _
                    ByVal detalleConcurrencias As String,  _
                    ByVal totalConcurrencias As Integer)
            MyBase.New
            Me.grados = grados
            Me.sueldoEnActividad = sueldoEnActividad
            Me.sueldo1981 = sueldo1981
            Me.cantidadTrienios = cantidadTrienios
            Me.porcentajeTrienios = porcentajeTrienios
            Me.asignacionTrieniosLey18263 = asignacionTrieniosLey18263
            Me.asignacionTrieniosLey18694 = asignacionTrieniosLey18694
            Me.porcentajeSobresueldo = porcentajeSobresueldo
            Me.sobresueldoLey18263 = sobresueldoLey18263
            Me.sobresueldoLey18694 = sobresueldoLey18694
            Me.porcentajeBonifMandoAdministracion = porcentajeBonifMandoAdministracion
            Me.bonifMandoAdministracionLey18263 = bonifMandoAdministracionLey18263
            Me.bonifMandoAdministracionLey18694 = bonifMandoAdministracionLey18694
            Me.porcentajeBonifAltoMando = porcentajeBonifAltoMando
            Me.bonifAltoMandoLey18263 = bonifAltoMandoLey18263
            Me.bonifAltoMandoLey18694 = bonifAltoMandoLey18694
            Me.aplicaPlanillaSuplementaria = aplicaPlanillaSuplementaria
            Me.planillaSuplementariaLey19699Actual = planillaSuplementariaLey19699Actual
            Me.planillaSuplementariaLey19699anio1981 = planillaSuplementariaLey19699anio1981
            Me.porcentajeAsignacionSOM = porcentajeAsignacionSOM
            Me.asignacionSOMLey18263 = asignacionSOMLey18263
            Me.asignacionSOMLey18694 = asignacionSOMLey18694
            Me.porcentajeAsigMinistroDeCorte = porcentajeAsigMinistroDeCorte
            Me.asigMinistroDeCorteLey18263 = asigMinistroDeCorteLey18263
            Me.asigMinistroDeCorteLey18694 = asigMinistroDeCorteLey18694
            Me.poseeTituloProf = poseeTituloProf
            Me.aegeLey18263 = aegeLey18263
            Me.aegeLey18694 = aegeLey18694
            Me.totalLey18263 = totalLey18263
            Me.totalParaDesahucio = totalParaDesahucio
            Me.cantidadAVOS = cantidadAVOS
            Me.montoAVOS = montoAVOS
            Me.porcentajeAVOS = porcentajeAVOS
            Me.reajusteHasta8_8 = reajusteHasta8_8
            Me.porcentajeReajusteDS376_1987 = porcentajeReajusteDS376_1987
            Me.montoReajusteDS376_1987 = montoReajusteDS376_1987
            Me.porcentajeReajusteDS321_1988 = porcentajeReajusteDS321_1988
            Me.montoReajusteDS321_1988 = montoReajusteDS321_1988
            Me.tipoDocUltimoReajuste = tipoDocUltimoReajuste
            Me.numeroDocUltimoReajuste = numeroDocUltimoReajuste
            Me.porcentajeUltimoReajuste = porcentajeUltimoReajuste
            Me.montoUltimoReajuste = montoUltimoReajuste
            Me.totalImponibleParcial = totalImponibleParcial
            Me.totalDesahucioSegunAvos = totalDesahucioSegunAvos
            Me.totalImponible = totalImponible
            Me.aegeNoImponible = aegeNoImponible
            Me.recibePlanillaSuplementariaDfl_1_68 = recibePlanillaSuplementariaDfl_1_68
            Me.planillaSuplementariaDfl_1_68 = planillaSuplementariaDfl_1_68
            Me.bonificacionCompensatoria = bonificacionCompensatoria
            Me.tipoDeBonifRiesgoEspecial = tipoDeBonifRiesgoEspecial
            Me.porcentajeBonifRiesgoEspecial = porcentajeBonifRiesgoEspecial
            Me.bonifRiesgoEspecial = bonifRiesgoEspecial
            Me.porcentajeAsigMinDeCorteNoImp = porcentajeAsigMinDeCorteNoImp
            Me.asigMinistroDeCorteNoImp = asigMinistroDeCorteNoImp
            Me.porcentajeAsigSOMnoImp = porcentajeAsigSOMnoImp
            Me.asignacionSOMnoImp = asignacionSOMnoImp
            Me.porcentajeSegundoSobresueldo = porcentajeSegundoSobresueldo
            Me.segundoSobresueldo = segundoSobresueldo
            Me.totalRemuneracion = totalRemuneracion
            Me.totalRemuneracionSegunAVOS = totalRemuneracionSegunAVOS
            Me.porcentajeAVOS2 = porcentajeAVOS2
            Me.pensionAotorgar = pensionAotorgar
            Me.conTopeSinTope = conTopeSinTope
            Me.distribucionCapredena = distribucionCapredena
            Me.distribucionFisco = distribucionFisco
            Me.distribucionTotal = distribucionTotal
            Me.mensualidadesDesahucio = mensualidadesDesahucio
            Me.montoMensualidadDesahucio = montoMensualidadDesahucio
            Me.subtotalDesahucio = subtotalDesahucio
            Me.cantidadAcciones = cantidadAcciones
            Me.montoUnitarioAcciones = montoUnitarioAcciones
            Me.subtotalAcciones = subtotalAcciones
            Me.desahucioApagar = desahucioApagar
            Me.mesesSgteTrienio = mesesSgteTrienio
            Me.diasSgteTrienio = diasSgteTrienio
            Me.siguienteTrienio = siguienteTrienio
            Me.detalleDeServicios = detalleDeServicios
            Me.aniosServiciosTotales = aniosServiciosTotales
            Me.mesesServiciosTotales = mesesServiciosTotales
            Me.diasServiciosTotales = diasServiciosTotales
            Me.enDiasServiciosTotales = enDiasServiciosTotales
            Me.proporcionServiciosTotales = proporcionServiciosTotales
            Me.detalleConcurrencias = detalleConcurrencias
            Me.totalConcurrencias = totalConcurrencias
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class calcularPorXmlRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="calcularPorXml", [Namespace]:="http://calculo.webServices.calculoRetiroWS.ssffaa.cl", Order:=0)>  _
        Public Body As WsCalculoRetiro.calcularPorXmlRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsCalculoRetiro.calcularPorXmlRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class calcularPorXmlRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public xmlInput As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal xmlInput As String)
            MyBase.New
            Me.xmlInput = xmlInput
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class calcularPorXmlResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="calcularPorXmlResponse", [Namespace]:="http://calculo.webServices.calculoRetiroWS.ssffaa.cl", Order:=0)>  _
        Public Body As WsCalculoRetiro.calcularPorXmlResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsCalculoRetiro.calcularPorXmlResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class calcularPorXmlResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public xmlOutput As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal xmlOutput As String)
            MyBase.New
            Me.xmlOutput = xmlOutput
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface CalculoRetiroWSChannel
        Inherits WsCalculoRetiro.CalculoRetiroWS, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CalculoRetiroWSClient
        Inherits System.ServiceModel.ClientBase(Of WsCalculoRetiro.CalculoRetiroWS)
        Implements WsCalculoRetiro.CalculoRetiroWS
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCalculoRetiro_CalculoRetiroWS_calcularPorParametros(ByVal request As WsCalculoRetiro.calcularPorParametrosRequest) As WsCalculoRetiro.calcularPorParametrosResponse Implements WsCalculoRetiro.CalculoRetiroWS.calcularPorParametros
            Return MyBase.Channel.calcularPorParametros(request)
        End Function
        
        Public Function calcularPorParametros( _
                    ByVal run As String,  _
                    ByVal institucion As String,  _
                    ByVal subInstitucion As String,  _
                    ByVal categoria As String,  _
                    ByVal escalafonCivil As String,  _
                    ByVal grado As String,  _
                    ByVal gradoJerarquico As Integer,  _
                    ByVal gradoEconomico As Integer,  _
                    ByVal esDeLinea As String,  _
                    ByVal fechaDeBaja As String,  _
                    ByVal cantidadDeAcciones As Integer,  _
                    ByVal tipoDeAcciones As String,  _
                    ByVal porcentajeDeSobresueldo As String,  _
                    ByVal porcentajeDeSegundoSobresueldo As String,  _
                    ByVal porcentajeDeAsignacionSOFSOM As String,  _
                    ByVal poseeAsigMinistroDeCorte As String,  _
                    ByVal sueldoIntegroMinistroDeCorte As Integer,  _
                    ByVal planillaSuplementariaLey19699 As String,  _
                    ByVal planillaSuplementariaDFL1_68 As String,  _
                    ByVal aniosCPDNyConsc As Integer,  _
                    ByVal mesesCPDNyConsc As Integer,  _
                    ByVal diasCPDNyConsc As Integer,  _
                    ByVal aniosDesahucio As Integer,  _
                    ByVal mesesDesahucio As Integer,  _
                    ByVal diasDesahucio As Integer,  _
                    ByVal otrasInstituciones As String,  _
                    ByVal abonos As String,  _
                    ByVal concurrencias As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef sueldoEnActividad As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef sueldo1981 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef cantidadTrienios As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef porcentajeTrienios As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef asignacionTrieniosLey18263 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef asignacionTrieniosLey18694 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef porcentajeSobresueldo As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef sobresueldoLey18263 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef sobresueldoLey18694 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef porcentajeBonifMandoAdministracion As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef bonifMandoAdministracionLey18263 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef bonifMandoAdministracionLey18694 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef porcentajeBonifAltoMando As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef bonifAltoMandoLey18263 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef bonifAltoMandoLey18694 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef aplicaPlanillaSuplementaria As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef planillaSuplementariaLey19699Actual As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef planillaSuplementariaLey19699anio1981 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef porcentajeAsignacionSOM As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef asignacionSOMLey18263 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef asignacionSOMLey18694 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef porcentajeAsigMinistroDeCorte As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef asigMinistroDeCorteLey18263 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef asigMinistroDeCorteLey18694 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef poseeTituloProf As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef aegeLey18263 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef aegeLey18694 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef totalLey18263 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef totalParaDesahucio As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef cantidadAVOS As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef montoAVOS As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef porcentajeAVOS As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef reajusteHasta8_8 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef porcentajeReajusteDS376_1987 As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef montoReajusteDS376_1987 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef porcentajeReajusteDS321_1988 As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef montoReajusteDS321_1988 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef tipoDocUltimoReajuste As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef numeroDocUltimoReajuste As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef porcentajeUltimoReajuste As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef montoUltimoReajuste As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef totalImponibleParcial As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef totalDesahucioSegunAvos As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef totalImponible As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef aegeNoImponible As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef recibePlanillaSuplementariaDfl_1_68 As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef planillaSuplementariaDfl_1_68 As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef bonificacionCompensatoria As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef tipoDeBonifRiesgoEspecial As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef porcentajeBonifRiesgoEspecial As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef bonifRiesgoEspecial As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef porcentajeAsigMinDeCorteNoImp As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef asigMinistroDeCorteNoImp As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef porcentajeAsigSOMnoImp As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef asignacionSOMnoImp As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef porcentajeSegundoSobresueldo As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef segundoSobresueldo As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef totalRemuneracion As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef totalRemuneracionSegunAVOS As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef porcentajeAVOS2 As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef pensionAotorgar As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef conTopeSinTope As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef distribucionCapredena As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef distribucionFisco As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef distribucionTotal As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef mensualidadesDesahucio As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef montoMensualidadDesahucio As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef subtotalDesahucio As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef cantidadAcciones As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef montoUnitarioAcciones As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef subtotalAcciones As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef desahucioApagar As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef mesesSgteTrienio As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef diasSgteTrienio As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef siguienteTrienio As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef detalleDeServicios As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef aniosServiciosTotales As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef mesesServiciosTotales As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef diasServiciosTotales As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef enDiasServiciosTotales As Integer,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef proporcionServiciosTotales As Double,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef detalleConcurrencias As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef totalConcurrencias As Integer) As String
            Dim inValue As WsCalculoRetiro.calcularPorParametrosRequest = New WsCalculoRetiro.calcularPorParametrosRequest()
            inValue.Body = New WsCalculoRetiro.calcularPorParametrosRequestBody()
            inValue.Body.run = run
            inValue.Body.institucion = institucion
            inValue.Body.subInstitucion = subInstitucion
            inValue.Body.categoria = categoria
            inValue.Body.escalafonCivil = escalafonCivil
            inValue.Body.grado = grado
            inValue.Body.gradoJerarquico = gradoJerarquico
            inValue.Body.gradoEconomico = gradoEconomico
            inValue.Body.esDeLinea = esDeLinea
            inValue.Body.fechaDeBaja = fechaDeBaja
            inValue.Body.cantidadDeAcciones = cantidadDeAcciones
            inValue.Body.tipoDeAcciones = tipoDeAcciones
            inValue.Body.porcentajeDeSobresueldo = porcentajeDeSobresueldo
            inValue.Body.porcentajeDeSegundoSobresueldo = porcentajeDeSegundoSobresueldo
            inValue.Body.porcentajeDeAsignacionSOFSOM = porcentajeDeAsignacionSOFSOM
            inValue.Body.poseeAsigMinistroDeCorte = poseeAsigMinistroDeCorte
            inValue.Body.sueldoIntegroMinistroDeCorte = sueldoIntegroMinistroDeCorte
            inValue.Body.planillaSuplementariaLey19699 = planillaSuplementariaLey19699
            inValue.Body.planillaSuplementariaDFL1_68 = planillaSuplementariaDFL1_68
            inValue.Body.aniosCPDNyConsc = aniosCPDNyConsc
            inValue.Body.mesesCPDNyConsc = mesesCPDNyConsc
            inValue.Body.diasCPDNyConsc = diasCPDNyConsc
            inValue.Body.aniosDesahucio = aniosDesahucio
            inValue.Body.mesesDesahucio = mesesDesahucio
            inValue.Body.diasDesahucio = diasDesahucio
            inValue.Body.otrasInstituciones = otrasInstituciones
            inValue.Body.abonos = abonos
            inValue.Body.concurrencias = concurrencias
            Dim retVal As WsCalculoRetiro.calcularPorParametrosResponse = CType(Me,WsCalculoRetiro.CalculoRetiroWS).calcularPorParametros(inValue)
            sueldoEnActividad = retVal.Body.sueldoEnActividad
            sueldo1981 = retVal.Body.sueldo1981
            cantidadTrienios = retVal.Body.cantidadTrienios
            porcentajeTrienios = retVal.Body.porcentajeTrienios
            asignacionTrieniosLey18263 = retVal.Body.asignacionTrieniosLey18263
            asignacionTrieniosLey18694 = retVal.Body.asignacionTrieniosLey18694
            porcentajeSobresueldo = retVal.Body.porcentajeSobresueldo
            sobresueldoLey18263 = retVal.Body.sobresueldoLey18263
            sobresueldoLey18694 = retVal.Body.sobresueldoLey18694
            porcentajeBonifMandoAdministracion = retVal.Body.porcentajeBonifMandoAdministracion
            bonifMandoAdministracionLey18263 = retVal.Body.bonifMandoAdministracionLey18263
            bonifMandoAdministracionLey18694 = retVal.Body.bonifMandoAdministracionLey18694
            porcentajeBonifAltoMando = retVal.Body.porcentajeBonifAltoMando
            bonifAltoMandoLey18263 = retVal.Body.bonifAltoMandoLey18263
            bonifAltoMandoLey18694 = retVal.Body.bonifAltoMandoLey18694
            aplicaPlanillaSuplementaria = retVal.Body.aplicaPlanillaSuplementaria
            planillaSuplementariaLey19699Actual = retVal.Body.planillaSuplementariaLey19699Actual
            planillaSuplementariaLey19699anio1981 = retVal.Body.planillaSuplementariaLey19699anio1981
            porcentajeAsignacionSOM = retVal.Body.porcentajeAsignacionSOM
            asignacionSOMLey18263 = retVal.Body.asignacionSOMLey18263
            asignacionSOMLey18694 = retVal.Body.asignacionSOMLey18694
            porcentajeAsigMinistroDeCorte = retVal.Body.porcentajeAsigMinistroDeCorte
            asigMinistroDeCorteLey18263 = retVal.Body.asigMinistroDeCorteLey18263
            asigMinistroDeCorteLey18694 = retVal.Body.asigMinistroDeCorteLey18694
            poseeTituloProf = retVal.Body.poseeTituloProf
            aegeLey18263 = retVal.Body.aegeLey18263
            aegeLey18694 = retVal.Body.aegeLey18694
            totalLey18263 = retVal.Body.totalLey18263
            totalParaDesahucio = retVal.Body.totalParaDesahucio
            cantidadAVOS = retVal.Body.cantidadAVOS
            montoAVOS = retVal.Body.montoAVOS
            porcentajeAVOS = retVal.Body.porcentajeAVOS
            reajusteHasta8_8 = retVal.Body.reajusteHasta8_8
            porcentajeReajusteDS376_1987 = retVal.Body.porcentajeReajusteDS376_1987
            montoReajusteDS376_1987 = retVal.Body.montoReajusteDS376_1987
            porcentajeReajusteDS321_1988 = retVal.Body.porcentajeReajusteDS321_1988
            montoReajusteDS321_1988 = retVal.Body.montoReajusteDS321_1988
            tipoDocUltimoReajuste = retVal.Body.tipoDocUltimoReajuste
            numeroDocUltimoReajuste = retVal.Body.numeroDocUltimoReajuste
            porcentajeUltimoReajuste = retVal.Body.porcentajeUltimoReajuste
            montoUltimoReajuste = retVal.Body.montoUltimoReajuste
            totalImponibleParcial = retVal.Body.totalImponibleParcial
            totalDesahucioSegunAvos = retVal.Body.totalDesahucioSegunAvos
            totalImponible = retVal.Body.totalImponible
            aegeNoImponible = retVal.Body.aegeNoImponible
            recibePlanillaSuplementariaDfl_1_68 = retVal.Body.recibePlanillaSuplementariaDfl_1_68
            planillaSuplementariaDfl_1_68 = retVal.Body.planillaSuplementariaDfl_1_68
            bonificacionCompensatoria = retVal.Body.bonificacionCompensatoria
            tipoDeBonifRiesgoEspecial = retVal.Body.tipoDeBonifRiesgoEspecial
            porcentajeBonifRiesgoEspecial = retVal.Body.porcentajeBonifRiesgoEspecial
            bonifRiesgoEspecial = retVal.Body.bonifRiesgoEspecial
            porcentajeAsigMinDeCorteNoImp = retVal.Body.porcentajeAsigMinDeCorteNoImp
            asigMinistroDeCorteNoImp = retVal.Body.asigMinistroDeCorteNoImp
            porcentajeAsigSOMnoImp = retVal.Body.porcentajeAsigSOMnoImp
            asignacionSOMnoImp = retVal.Body.asignacionSOMnoImp
            porcentajeSegundoSobresueldo = retVal.Body.porcentajeSegundoSobresueldo
            segundoSobresueldo = retVal.Body.segundoSobresueldo
            totalRemuneracion = retVal.Body.totalRemuneracion
            totalRemuneracionSegunAVOS = retVal.Body.totalRemuneracionSegunAVOS
            porcentajeAVOS2 = retVal.Body.porcentajeAVOS2
            pensionAotorgar = retVal.Body.pensionAotorgar
            conTopeSinTope = retVal.Body.conTopeSinTope
            distribucionCapredena = retVal.Body.distribucionCapredena
            distribucionFisco = retVal.Body.distribucionFisco
            distribucionTotal = retVal.Body.distribucionTotal
            mensualidadesDesahucio = retVal.Body.mensualidadesDesahucio
            montoMensualidadDesahucio = retVal.Body.montoMensualidadDesahucio
            subtotalDesahucio = retVal.Body.subtotalDesahucio
            cantidadAcciones = retVal.Body.cantidadAcciones
            montoUnitarioAcciones = retVal.Body.montoUnitarioAcciones
            subtotalAcciones = retVal.Body.subtotalAcciones
            desahucioApagar = retVal.Body.desahucioApagar
            mesesSgteTrienio = retVal.Body.mesesSgteTrienio
            diasSgteTrienio = retVal.Body.diasSgteTrienio
            siguienteTrienio = retVal.Body.siguienteTrienio
            detalleDeServicios = retVal.Body.detalleDeServicios
            aniosServiciosTotales = retVal.Body.aniosServiciosTotales
            mesesServiciosTotales = retVal.Body.mesesServiciosTotales
            diasServiciosTotales = retVal.Body.diasServiciosTotales
            enDiasServiciosTotales = retVal.Body.enDiasServiciosTotales
            proporcionServiciosTotales = retVal.Body.proporcionServiciosTotales
            detalleConcurrencias = retVal.Body.detalleConcurrencias
            totalConcurrencias = retVal.Body.totalConcurrencias
            Return retVal.Body.grados
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsCalculoRetiro_CalculoRetiroWS_calcularPorXml(ByVal request As WsCalculoRetiro.calcularPorXmlRequest) As WsCalculoRetiro.calcularPorXmlResponse Implements WsCalculoRetiro.CalculoRetiroWS.calcularPorXml
            Return MyBase.Channel.calcularPorXml(request)
        End Function
        
        Public Function calcularPorXml(ByVal xmlInput As String) As String
            Dim inValue As WsCalculoRetiro.calcularPorXmlRequest = New WsCalculoRetiro.calcularPorXmlRequest()
            inValue.Body = New WsCalculoRetiro.calcularPorXmlRequestBody()
            inValue.Body.xmlInput = xmlInput
            Dim retVal As WsCalculoRetiro.calcularPorXmlResponse = CType(Me,WsCalculoRetiro.CalculoRetiroWS).calcularPorXml(inValue)
            Return retVal.Body.xmlOutput
        End Function
    End Class
End Namespace
