package cl.ssffaa.calculoRetiroWS.util.enums;

public class EnumTiposDePersonal {

	public static  String OFICIALES  = "OFICIALES";
	public static  String CUADRO_PERMANENTE  = "CUADRO PERMANENTE Y GENTE DE MAR";
	public static  String TROPA_PROFESIONAL  = "TROPA PROFESIONAL";
	public static  String CIVILES_PROF_UNIV  = "EMPLEADOS CIVILES PROFESIONALES UNIVERSITARIOS";
	public static  String CIVILES_TEC_ADM_PLANTA_Y_CONTRATA  = "EMPLEADOS CIVILES TÉCNICOS O ADMINISTRATIVOS DE PLANTA Y CONTRATA";
	public static  String CIVILES_PROF_UNIV_SUBSEC  = "EMPLEADOS CIVILES PROFESIONALES UNIVERSITARIOS SUBSECRETARÍAS";
	public static  String CIVILES_TEC_ADM_PLANTA_Y_CONTRATA_SUBSEC  = "EMPLEADOS CIVILES TÉCNICOS O ADMINISTRATIVOS DE PLANTA Y CONTRATA SUBSECRETARÍAS";
	public static  String CIVIL_GENERAL  = "EMPLEADO CIVIL GENERAL";
}
